"""Add timestamp column to Scan model

Revision ID: 2bf91dd2c7e5
Revises: 
Create Date: 2024-10-27 15:06:37.557161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf91dd2c7e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
